import Head from "next/head"
import Image from "next/image"
import { Navbar } from "components/navbar"
import { Container } from "@nextui-org/react"

export const Layout = ({
  children
}: {
  children: React.ReactNode
}) => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container css={{
        maxWidth: '960px'
      }}>
        {children}
      </Container>
      <footer style={{
        position: 'relative',
        display: 'flex',
        justifyContent: 'center'
      }}>
        <Navbar />
      </footer>
    </>
  )
}
