import Head from "next/head"
import { Navbar } from "components/navbar"

export const Layout = ({
  children
}: {
  children: React.ReactNode
}) => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
      <footer style={{
          position: 'relative',
          display: 'flex',
          justifyContent: 'center'
        }}>
        <Navbar />
      </footer>
    </>
  )
}
