import type { NextPage } from 'next'
import Head from 'next/head'
import { MyComponent } from '../components/button'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>My Commands</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyComponent />
    </>
  )
}

export default Home
