import type { NextPage } from 'next'
import Head from 'next/head'
import { Text, Container, Spacer, Button, Avatar, Card, Row } from '@nextui-org/react';
import { List, AddCircledOutline } from 'iconoir-react';

const Add: NextPage = () => {
  return (
    <>
      <Head>
        <title>Add</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <footer style={{position: 'relative'}}>
        <Container css={{position: 'fixed', bottom: '4rem'}}>
          <Card>
            <Row justify="space-between" align="center">
              <List />
              <AddCircledOutline height={36} width={36}/>
              <Avatar bordered rounded text="Beto" size="sm" color="primary" />
            </Row>
          </Card>
        </Container>
      </footer>
    </>
  )
}

export default Add
