import type { NextPage } from 'next'
import Head from 'next/head'
import { Text, Container, Spacer, Grid, Avatar, Card, Row, Input, Textarea, Button } from '@nextui-org/react';
import { List, AddCircledOutline } from 'iconoir-react';

const Add: NextPage = () => {
  const CategoryItems = () => {
     return (
      <Card shadow={false} css={{borderRadius: '25%', width: 'fit-content', fontSize: '12px', padding: '$0'}}>Git</Card>
    )
  }
  return (
    <>
      <Head>
        <title>Add</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{paddingTop: '150px'}}>
        <Container>
          <Input clearable labelPlaceholder="Agrega un comando" width="100%" css={{fontFamily: 'mono'}} />
        </Container>
        <Spacer y={2}/>
        <Container>
          <Text small css={{marginLeft: '7px', fontFamily: 'mono', fontWeight: 'light'}}>Elige una categoría</Text>
          <Spacer y={0.3}/>
          <Card shadow={false} css={{backgroundColor: '#f4f4f4'}}>
            <Grid.Container gap={1} >
              <Grid sm={3}><CategoryItems /></Grid>
              <Grid sm={3}><CategoryItems /></Grid>
              <Grid sm={3}><CategoryItems /></Grid>
              <Grid sm={3}><CategoryItems /></Grid>
              <Grid sm={3}><CategoryItems /></Grid>
            </Grid.Container>
          </Card>
        </Container>
        <Spacer y={2}/>
        <Container>
          <Textarea labelPlaceholder="De qué trata el comando?" status="default" width='100%' rows={6} css={{fontFamily: 'mono'}}/>
        </Container>
        <Spacer y={2}/>
        <Container justify="center" display="flex">
          <Button>Guardar</Button>
        </Container>
      </main>
      <footer style={{position: 'relative'}}>
        <Container css={{position: 'fixed', bottom: '4rem'}}>
          <Card>
            <Row justify="space-between" align="center">
              <List />
              <AddCircledOutline height={36} width={36}/>
              <Avatar bordered rounded text="Beto" size="sm" color="primary" />
            </Row>
          </Card>
        </Container>
      </footer>
    </>
  )
}

export default Add
